#if IG_C106 || IG_C109 || IG_C201 || IG_C301 || IG_C302 // Auto generated by AddMacroForInstantGameFiles.exe

namespace Unity.AutoStreaming.CloudContentDelivery
{
    internal enum CCDResourceType
    {
        None = 0,
        StreamedResource = 1,
        AddressableAsset = 2,
        CustomCloudAssets = 3,
        InstantGame = 4
    }

    internal class CCDInfo
    {
        internal static string ApiHost => IsOversea ? "https://assetstreaming-oversea.unity.cn/" : "https://assetstreaming.unity.cn/";

        //cos backend
        internal static bool IsOversea { get; set; }
        internal const string CosAppId = "1301029430";
        internal static string CosRegion => IsOversea ? "na-siliconvalley" : "ap-shanghai";
        internal static string CosBucket => IsOversea ? "asset-streaming-oversea-1301029430" : "asset-streaming-1301029430";

        //lanyun backend
        internal static string WcsUploadHost = "lanyun.up28.v1.wcsapi.com";
        internal static string WcsManageHost = "lanyun.mgr28.v1.wcsapi.com";
    }
}

#endif  // IG_C106 || IG_C109 || IG_C201 || IG_C301 || IG_C302, Auto generated by AddMacroForInstantGameFiles.exe
