#if IG_C106 || IG_C109 || IG_C201 || IG_C301 || IG_C302 // Auto generated by AddMacroForInstantGameFiles.exe

using System;
using System.IO;
using System.Net;
using UnityEditor;
using UnityEngine;

namespace Unity.AutoStreaming.CloudContentDelivery
{
    [Serializable]
    internal class Project
    {
        public string UserId;
        public string Key;
        public string KeyHash;
        public string ProjectUUID;
        public string CreatedAt;
        public string Backend;

        public static Project LoadProject(string instantGameProjectId)
        {
            string url = string.Format("{0}api/v1/instantgame/id/{1}/coskey", CCDInfo.ApiHost, instantGameProjectId);
            try
            {
                HttpWebRequest request = (HttpWebRequest)WebRequest.Create(url);
                request.Proxy = null;
                request.Method = "GET";
                using (HttpWebResponse resp = (HttpWebResponse)request.GetResponse())
                {
                    if (resp.StatusCode.Equals(HttpStatusCode.OK))
                    {
                        string strJson;
                        using (Stream stream = resp.GetResponseStream())
                        {
                            using (StreamReader reader = new StreamReader(stream))
                            {
                                strJson = reader.ReadToEnd();
                            }
                        }
                        var obj = JsonUtility.FromJson<Project>(strJson);
                        if (obj != null)
                        {
                            Util.backend = obj.Backend;
                            return obj;
                        }
                    }
                    else
                    {
                        Debug.LogError("Failed loading CCD Project.");
                    }
                }
            }
            catch (Exception e)
            {
                EditorUtility.DisplayDialog("Load CCD Project Error", e.Message, "OK");
            }
            return null;
        }
    }

    [Serializable]
    internal class ProjectInfo
    {
        public string projectGuid;
        public string Backend;

        public static ProjectInfo LoadProjectInfo(string cosKey)
        {
            if (string.IsNullOrEmpty(cosKey))
            {
                return null;
            }
            string url = string.Format("{0}api/v1/users/me/projectguid", CCDInfo.ApiHost);

            try
            {
                using (HttpWebResponse resp = (HttpWebResponse)Util.GetHttpWebRequest4CCDThreaded(cosKey, url, "GET").GetResponse())
                {
                    if (resp.StatusCode.Equals(HttpStatusCode.OK))
                    {
                        string strJson;
                        using (Stream stream = resp.GetResponseStream())
                        {
                            using (StreamReader reader = new StreamReader(stream))
                            {
                                strJson = reader.ReadToEnd();
                            }
                        }
                        var obj = JsonUtility.FromJson<ProjectInfo>(strJson);
                        if (obj != null)
                        {
                            Util.backend = obj.Backend;
                            return obj;
                        }
                    }
                    else
                    {
                        Debug.LogError("Failed loading CCD Project Info.");
                    }
                }
            }
            catch (Exception e)
            {
                EditorUtility.DisplayDialog("Load CCD Project Info", e.Message, "OK");
            }
            return null;
        }
    }
}

#endif  // IG_C106 || IG_C109 || IG_C201 || IG_C301 || IG_C302, Auto generated by AddMacroForInstantGameFiles.exe
