#if IG_C106 || IG_C109 || IG_C201 || IG_C301 || IG_C302 // Auto generated by AddMacroForInstantGameFiles.exe

using System;
using UnityEditor;
using UnityEngine;

namespace Unity.AutoStreaming
{
    internal class CreateBadgePopup : PopupWindowContent
    {
        private const int k_Padding = 5;
        private const int k_TextFieldWidth = 115;

        private string m_BadgeName = string.Empty;

        public event Action<string> OnBadgeCreated;

        public override Vector2 GetWindowSize()
        {
            return new Vector2(300, 60);
        }

        public override void OnGUI(Rect rect)
        {
            GUILayout.Space(k_Padding * 2);

            GUILayout.BeginHorizontal();
            GUILayout.Space(k_Padding);
            EditorGUILayout.LabelField("Badge Name", GUILayout.Width(k_TextFieldWidth));
            GUILayout.Space(k_Padding);
            m_BadgeName = EditorGUILayout.TextField(m_BadgeName);
            GUILayout.Space(k_Padding);
            GUILayout.EndHorizontal();

            GUILayout.Space(k_Padding);

            GUILayout.BeginHorizontal();
            GUILayout.Space(k_Padding);
            if (GUILayout.Button("Create"))
            {
                string id = ASCCDHelper.GetLatestReleaseId();
                if (string.IsNullOrEmpty(id))
                {
                    id = ASCCDHelper.CreateRelease("Create Badge: " + m_BadgeName);
                }
                ASCCDHelper.CreateOrUpdateBadge(m_BadgeName.Replace('.', '_'), id);
                OnBadgeCreated?.Invoke(m_BadgeName.Replace('.', '_'));
                editorWindow.Close();
            }
            GUILayout.Space(k_Padding);
            GUILayout.EndHorizontal();
        }
    }
}

#endif  // IG_C106 || IG_C109 || IG_C201 || IG_C301 || IG_C302, Auto generated by AddMacroForInstantGameFiles.exe
